### ISSUE TITLE
Please add 1.21.1 support i really need it

### ISSUE THREAD

**Issue by Leeewith3Es** [Folia-Inquisitors/WorldEdit-Folia#4]
### The Problem

Please add 1.21.1 support i really need it

### A Solution

Please add 1.21.1 support i really need it

### Alternatives

Please add 1.21.1 support i really need it

### Anything Else?

Please add 1.21.1 support i really need it

**Comment by Aruvelut-123** [comment]
It works on my folia 1.21.1 server just lose a lot of functions.

**Comment by HYDeath** [comment]
Hopefully it will be updated to 1.21.1 as there are too many features missing and some things that need to be used are not available. @Yomamaeatstoes

**Comment by VanillaChan6571** [comment]
@Leeewith3Es you can always add this into your config.yml if you wish. You been warned.

```
allow-editing-on-unsupported-versions: "I accept that I will receive no support with this flag enabled."
```

**Comment by VanillaChan6571** [comment]
#5

**Comment by Yomamaeatstoes** [comment]
> @Leeewith3Es you can always add this into your config.yml if you wish. You been warned.
> 
> ```
> allow-editing-on-unsupported-versions: "I accept that I will receive no support with this flag enabled."
> ```
> 
> This will allow you to use most of the commands again.

Doing this would be a good work around.

**Comment by Yomamaeatstoes** [comment]
**Hello,** @Leeewith3Es @VanillaChan6571 @Aruvelut-123 

**The WorldEdit currently in the "Releases" should work on 1.21.1 just fine. I have been using it. In the meanwhile, you could benefit from following @VanillaChan6571 advice and doing "allow-editing-on-unsupported-versions: "I accept that I will receive no support with this flag enabled."** _Since this is a fork, you wouldn't get much if any support anyways from WE Devs. This should bring some features back, I will look into getting this project finished eventually. When it is, I will do a PR back into WE for review._

**Comment by Dg32z** [comment]
schematic cannot  ):

**Comment by cgw2023** [comment]
Try this, I changed something and compiled it.
you don't need `allow-editing-on-unsupported-versions` on config.yml , you can use schemetic on folia 1.21.1
[we-folia-7.4.0-1.21.1.zip](https://github.com/user-attachments/files/17495585/we-folia-7.4.0-1.21.1.zip)

**Comment by Dg32z** [comment]
> Try this, I changed something and compiled it. you don't need on config.yml , you can use schemetic on folia 1.21.1 [we-folia-7.4.0-1.21.1.zip](https://github.com/user-attachments/files/17495585/we-folia-7.4.0-1.21.1.zip) let me know if it is working properly`allow-editing-on-unsupported-versions`

cannot work
